---
- name: Install Docker  # noqa: schema[playbook]
  hosts: personal:work:selfhost
  become: true
  become_method: sudo
  become_user: ansible
  vars_prompt:
    - name: "ans_pass"
      prompt: "Enter Ansible sudo Password"
      private: true
  vars:
    ansible_become_password: "{{ ans_pass }}"
  tasks:
    - name: Install Docker  # noqa: risky-shell-pipe no-changed-when
      become: true
      ansible.builtin.shell: |
        apt update
        apt install -y ca-certificates curl gnupg lsb-release
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg &&
        echo "
          deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
          $(lsb_release -cs) stable
        " | tee /etc/apt/sources.list.d/docker.list > /dev/null &&
        apt update
        apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
